<h1 style="font-size: 33px;">Working with Large Datasets in Python Using Pandas</h1>

<h1 style="font-size: 31px;">1. What is Pandas</h1>

Pandas is an open-source Python library for data manipulation and analysis, offering powerful data structures like Series (one-dimensional) and DataFrame (two-dimensional) for handling structured data efficiently.

It simplifies tasks such as data cleaning, transformation, and analysis by providing functions for filtering, merging, and handling missing values. Built on top of NumPy, Pandas ensures high performance and flexibility, making it an essential tool for data science and machine learning applications.

<h1 style="font-size: 31px;">Introduction to NumPy</h1>

## What is NumPy ?

NumPy (Numerical Python) is a fundamental library for numerical computing in Python. It enables efficient handling of large datasets using arrays and provides optimized functions for mathematical operations.

## Why Use NumPy ?

* Faster computations than Python lists
* Supports multi-dimensional arrays for structured data
* Provides built-in mathematical functions for easy calculations
* Optimized memory usage for handling large datasets
* Widely used in data science and machine learning

## Installing NumPy

To install NumPy, use the following command:

In [ ]:
pip install numpy

## Importing NumPy

In [ ]:
import numpy as np

## Creating a NumPy Array

A NumPy array is a collection of values stored in an efficient array structure:

In [307]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]

## Basic Operations with NumPy

NumPy provides various operations, such as:

- mean(), median(), std() for statistical calculations

- reshape() to modify array dimensions

- linspace() to create evenly spaced values

In [310]:
# Creating an array
arr = np.array([20, 40, 60, 80, 10])

In [311]:
# Performing basic arithmetic
print("Array + 8:", arr + 8)  # Adds 8 to each element  
print("Array * 5:", arr * 5)  # Multiplies each element by 5  
print("Mean of array:", np.mean(arr))  # Calculates mean  
print("Standard Deviation:", np.std(arr))  # Calculates standard deviation

Array + 8: [28 48 68 88 18]
Array * 5: [100 200 300 400  50]
Mean of array: 42.0
Standard Deviation: 25.612496949731394

<h1 style="font-size: 31px;">2. Installing and Importing Pandas</h1>

## Installing Pandas

If Pandas is not already installed, you can install it using:

In [315]:
pip install pandas

Requirement already satisfied: pandas in c:\users\maila divya\onedrive\documents\new folder\new folder\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in c:\users\maila divya\onedrive\documents\new folder\new folder\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maila divya\onedrive\documents\new folder\new folder\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\maila divya\onedrive\documents\new folder\new folder\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\maila divya\onedrive\documents\new folder\new folder\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\maila divya\onedrive\documents\new folder\new folder\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

## Importing the Pandas Library

In [317]:
# Importing Pandas
import pandas as pd

## Checking Pandas Version

In [319]:
# Displaying Pandas version
print(pd.__version__)

2.2.2

<h1 style="font-size: 31px;">3. Loading Data into a Pandas DataFrame</h1>

## What is a DataFrame?

A DataFrame is a two-dimensional labeled data structure, similar to a spreadsheet or SQL table, where data is stored in rows and columns.

## Reading a CSV File into a DataFrame

In [324]:
df=pd.read_csv("C:/Users/Maila Divya/Downloads/TMDB_movie_dataset_v11.csv")  # Loading dataset

In [325]:
df
# Displaying the DataFrame

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,761152,The Animator as Musician,0.000,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,The Animator as Musician,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,NaN,Documentary,ONF | NFB,NaN,NaN,NaN
1194389,761153,The Beastmaster Chronicles,0.000,0,Released,2020-11-27,0,82,False,NaN,...,The Beastmaster Chronicles,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,NaN,Documentary,Vinegar Syndrome,United States of America,English,NaN
1194390,761155,Under the Great Oak,0.000,0,Released,2019-08-03,0,53,False,NaN,...,Under the Great Oak,A small town wrestles with the responsibility ...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1194391,761158,Dance of the Cookoos,0.000,0,Released,1982-01-01,0,0,False,NaN,...,Dance of the cookoos,Dance of the Cookoos is merged a cinematic cro...,1.186,NaN,NaN,Comedy,Carsten Krüger Film,NaN,NaN,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN

<h1 style="font-size: 31px;">4. Exploring the DataFrame</h1>

## Displaying Data

- df.head() → Displays the first five rows

- df.tail() → Displays the last five rows

In [329]:
df.head(100) 
# Display first 100 rows

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,18785,The Hangover,7.312,15812,Released,2009-06-02,469310836,100,False,/2o0PKGmnSgCGkzoSePNAqse8Ure.jpg,...,The Hangover,When three friends finally come to after a rau...,72.655,/uluhlXubGu1VxU63X9VHCLWDAYP.jpg,Some guys just can't handle Vegas.,Comedy,"Legendary Pictures, Green Hat Films, Warner Br...","Germany, United States of America",English,"blackjack, stag night, lost weekend, chapel, h..."
96,1891,The Empire Strikes Back,8.400,15773,Released,1980-05-20,538400000,124,False,/aJCtkxLLzkk1pECehVjKHA2lBgw.jpg,...,The Empire Strikes Back,"The epic saga continues as Luke Skywalker, in ...",35.265,/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg,The Adventure Continues...,"Adventure, Action, Science Fiction",Lucasfilm Ltd.,United States of America,English,"rebellion, android, spacecraft, asteroid, rebe..."
97,808,Shrek,7.730,15765,Released,2001-05-18,487853320,90,False,/sRvXNDItGlWCqtO3j6wks52FmbD.jpg,...,Shrek,It ain't easy bein' green -- especially if you...,94.456,/dyhaB19AICF7TO7CK2aD6KfymnQ.jpg,The greatest fairy tale never told.,"Animation, Comedy, Fantasy, Adventure, Family","DreamWorks Pictures, Pacific Data Images, Drea...",United States of America,English,"princess, magic, fairy tale, donkey, liberatio..."
98,2062,Ratatouille,7.809,15728,Released,2007-06-28,623726000,111,False,/xgDj56UWyeWQcxQ44f5A3RTWuSs.jpg,...,Ratatouille,"Remy, a resident of Paris, appreciates good fo...",82.488,/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg,He's dying to become a chef.,"Animation, Comedy, Family, Fantasy","Pixar, Walt Disney Pictures",United States of America,"English, French","work, sibling relationship, paris, france, exp..."
99,207703,Kingsman: The Secret Service,7.636,15664,Released,2014-12-13,414351546,129,False,/dGXKgxWmiPRZkxphtMvBuCEeLU0.jpg,...,Kingsman: The Secret Service,The story of a super-secret spy organization t...,56.288,/ay7xwXn1G9fzX9TUBlkGA584rGi.jpg,Manners maketh man.,"Crime, Comedy, Action, Adventure","20th Century Fox, Marv Films, Cloudy Productio...","United Kingdom, United States of America","Arabic, English","great britain, spy, secret organization, secre..."

In [330]:
df.tail(100) 
# Display last 100 rows

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
1194293,761068,Deep Woods Inn,0.0,0,Released,1998-01-01,0,80,True,NaN,...,Deep Woods Inn,"Tattooed tough guy Russo, one of the nastiest ...",0.860,/222kH3ngA7mgJWQKgsPLxqRJaFt.jpg,NaN,NaN,Catalina Video,United States of America,English,gay pornography
1194294,761069,Clarice Lispector: A Descoberta do Mundo,0.0,0,Released,2023-03-13,0,102,False,NaN,...,Clarice Lispector: A Descoberta do Mundo,Documentary essay made from several cuts of in...,0.600,/bUZpHGllDEptp6WZhyi9cGenkkO.jpg,NaN,Documentary,Zest Artes e Comunicação,Brazil,Portuguese,clarice lispector
1194295,761071,Casino of Lust,0.0,0,Released,1984-01-01,0,80,True,NaN,...,Casino of Lust,Gambling has never been quite so exhilarating ...,0.600,/ucKUsXR1TuJnIfNSPL6IIWv7y9n.jpg,"Betting the ""Come Line"" Never Paid Off Like This!",NaN,Sheer Essence,United States of America,NaN,NaN
1194296,761073,The Casting Couch,0.0,0,Released,1983-01-01,0,84,True,NaN,...,The Casting Couch,Ron Jeremy directs and stars in this hilarious...,0.654,/uqdv9j5vgtOpiqLfdpOD0YRjR8l.jpg,"""Girl, I'm gonna make you a star!... By the wa...",NaN,NaN,United States of America,NaN,NaN
1194297,761074,COCO BEAT,0.0,0,Released,NaN,0,0,False,NaN,...,COCO BEAT,A Magical Sandwich Chase,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,761152,The Animator as Musician,0.0,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,The Animator as Musician,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,NaN,Documentary,ONF | NFB,NaN,NaN,NaN
1194389,761153,The Beastmaster Chronicles,0.0,0,Released,2020-11-27,0,82,False,NaN,...,The Beastmaster Chronicles,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,NaN,Documentary,Vinegar Syndrome,United States of America,English,NaN
1194390,761155,Under the Great Oak,0.0,0,Released,2019-08-03,0,53,False,NaN,...,Under the Great Oak,A small town wrestles with the responsibility ...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1194391,761158,Dance of the Cookoos,0.0,0,Released,1982-01-01,0,0,False,NaN,...,Dance of the cookoos,Dance of the Cookoos is merged a cinematic cro...,1.186,NaN,NaN,Comedy,Carsten Krüger Film,NaN,NaN,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.0,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN

## Checking DataFrame Information

The info() function provides an overview of the dataset, including column names, data types, and missing values.

In [333]:
print("DataFrame Info:")
df.info()

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194393 entries, 0 to 1194392
Data columns (total 24 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1194393 non-null  int64
 1   title                 1194380 non-null  object
 2   vote_average          1194393 non-null  float64
 3   vote_count            1194393 non-null  int64
 4   status                1194393 non-null  object
 5   release_date          982374 non-null   object
 6   revenue               1194393 non-null  int64
 7   runtime               1194393 non-null  int64
 8   adult                 1194393 non-null  bool
 9   backdrop_path         312774 non-null   object
 10  budget                1194393 non-null  int64
 11  homepage              125735 non-null   object
 12  imdb_id               616333 non-null   object
 13  original_language     1194393 non-null  object
 14  original_title        1194380 non-null  object
 15  overview              944421 non-null   object
 16  popularity            1194393 non-null  float64
 17  poster_path           806432 non-null   object
 18  tagline               167274 non-null   object
 19  genres                705029 non-null   object
 20  production_companies  532727 non-null   object
 21  production_countries  653511 non-null   object
 22  spoken_languages      674020 non-null   object
 23  keywords              316587 non-null   object
dtypes: bool(1), float64(2), int64(5), object(16)
memory usage: 210.7+ MB

## Summary Statistics

The describe() function provides statistical insights into numerical columns:

In [336]:
print("\nSummary Statistics:")
df.describe()

Summary Statistics:

,id,vote_average,vote_count,revenue,runtime,budget,popularity
count,1.194393e+06,1.194393e+06,1.194393e+06,1.194393e+06,1.194393e+06,1.194393e+06,1.194393e+06
mean,7.735426e+05,1.801781e+00,1.795962e+01,6.753187e+05,4.689109e+01,2.622916e+05,1.198448e+00
std,4.128542e+05,2.986139e+00,3.107406e+02,1.834429e+07,6.153247e+01,5.110289e+06,7.403951e+00
min,2.000000e+00,0.000000e+00,0.000000e+00,-1.200000e+01,-2.800000e+01,0.000000e+00,0.000000e+00
25%,4.281460e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.000000e-01
50%,7.805880e+05,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+01,0.000000e+00,6.000000e-01
75%,1.143584e+06,4.300000e+00,1.000000e+00,0.000000e+00,8.800000e+01,0.000000e+00,8.710000e-01
max,1.450920e+06,1.000000e+01,3.449500e+04,5.000000e+09,1.440000e+04,1.000000e+09,2.994357e+03

## Checking Data Types of Columns

Each column in a DataFrame has a specific data type:

In [339]:
df.dtypes

id                        int64
title                    object
vote_average            float64
vote_count                int64
status                   object
release_date             object
revenue                   int64
runtime                   int64
adult                      bool
backdrop_path            object
budget                    int64
homepage                 object
imdb_id                  object
original_language        object
original_title           object
overview                 object
popularity              float64
poster_path              object
tagline                  object
genres                   object
production_companies     object
production_countries     object
spoken_languages         object
keywords                 object
dtype: object

<h1 style="font-size: 31px;">5. Selecting Specific Columns in a DataFrame</h1>

## Selecting a Single Column

In [346]:
#Selecting Columns:
#Use df['column'] to select data.
df['budget']      
# Selecting the 'budget' column

0          160000000
1          165000000
2          185000000
3          237000000
4          220000000
             ...
1194388            0
1194389            0
1194390            0
1194391            0
1194392            0
Name: budget, Length: 1194393, dtype: int64

## Selecting Multiple Columns

In [355]:
#Use df[['col1', 'col2']] to select multiple columns.
df[['id', 'vote_count']]

              id  vote_count
0          27205       34495
1         157336       32571
2            155       30619
3          19995       29815
4          24428       29166
...          ...         ...
1194388   761152           0
1194389   761153           0
1194390   761155           0
1194391   761158           0
1194392  1450576           0

[1194393 rows x 2 columns]

## Selecting Multiple Columns for a Specific Row Range

In [376]:
#Selecting multiple columns for the rows from 150000 to 150019
df[['id', 'popularity', 'runtime']][150000:150019]

            id  popularity  runtime
150000  346281       0.600      110
150001  528492       0.600        0
150002  346279       0.681       13
150003  279070       0.600        1
150004  323585       0.600       13
150005  346267       0.683       11
150006  279067       0.681       88
150007  528590       2.653       45
150008  528598       0.600       26
150009  528604       2.059       24
150010  346257       0.600       20
150011   79599       5.303       52
150012  528627       0.682       95
150013  279052       0.953       99
150014  346164       1.316       75
150015  140248       2.109       68
150016   79587       1.698      100
150017   79577       1.068       97
150018  150514       0.600       89

In [378]:
# Selecting 'title', 'vote_average', and 'revenue' columns for every alternate row within the range 10000 to 10019
df[['title', 'vote_average', 'revenue']].iloc[10000:10019:2]

                             title  vote_average  revenue
10000               Precious Cargo         5.113   567064
10002                  Il vegetale         5.700  8475827
10004                   Wrong Cops         6.152        0
10006  Ewoks: The Battle for Endor         5.342        0
10008                      Threads         7.592        0
10010       Hannah Gadsby: Nanette         7.988        0
10012                  Don Camillo         7.667        0
10014        Poveri ma ricchissimi         5.682        0
10016                Apartment 143         5.197  4132000
10018           Dangerous Liaisons         5.840        0

In [380]:
df[['title', 'vote_average', 'revenue']].iloc[0:260919:200000]  
# Selecting 'title', 'vote_average', and 'revenue' with a step of 200000

            title  vote_average    revenue
0       Inception         8.364  825532764
200000  Kidnapped         6.000          0

<h1 style="font-size: 31px;">6. Filtering Rows in a Dataset</h1>

## Filtering Rows Based on a Condition

In [398]:
df[df['status'] == 'Released']   
# Select only rows where the movie status is 'Released'

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194387,761151,Usted tiene ojos de mujer fatal,0.000,0,Released,1962-01-01,0,0,False,NaN,...,Usted tiene ojos de mujer fatal,NaN,1.170,/uyx7yQzCtUGPDWXKEmg8nGJeQeB.jpg,NaN,Comedy,C.I.C.E.,Spain,Spanish,NaN
1194388,761152,The Animator as Musician,0.000,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,The Animator as Musician,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,NaN,Documentary,ONF | NFB,NaN,NaN,NaN
1194389,761153,The Beastmaster Chronicles,0.000,0,Released,2020-11-27,0,82,False,NaN,...,The Beastmaster Chronicles,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,NaN,Documentary,Vinegar Syndrome,United States of America,English,NaN
1194390,761155,Under the Great Oak,0.000,0,Released,2019-08-03,0,53,False,NaN,...,Under the Great Oak,A small town wrestles with the responsibility ...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1194391,761158,Dance of the Cookoos,0.000,0,Released,1982-01-01,0,0,False,NaN,...,Dance of the cookoos,Dance of the Cookoos is merged a cinematic cro...,1.186,NaN,NaN,Comedy,Carsten Krüger Film,NaN,NaN,NaN

## Filtering Rows to Exclude Specific Values (Based on Movie Dataset)

In [404]:
df[df["status"].isin(["Canceled", "Post Production"])]    
# Excludes rows where the 'status' is either 'Canceled' or 'Post Production'

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
182439,43217,Coexist,4.8,2,Post Production,NaN,0,53,False,NaN,...,Coexist,Coexist tells the emotional stories of women w...,0.600,NaN,"When hate persists, how will you coexist?","Documentary, History, War",NaN,"United States of America, Rwanda","English, Kinyarwanda","rwanda, rwandan genocide"
188386,389510,Godplex,10.0,2,Post Production,NaN,0,95,False,NaN,...,Godplex,"Inspired by ‘elephant consciousness’, Clark Du...",1.159,NaN,"Dreams are free, reality burns.","Drama, Thriller",InMediaRes,"India, Australia, New Zealand",NaN,"road trip, art house"
217292,280035,Beardo,5.2,2,Post Production,NaN,0,40,False,NaN,...,Beardo,A documentary on the World Beard and Moustache...,0.658,NaN,A documentary about the World Beard and Mousta...,Documentary,DIGICO Shoot | Post | Design,United States of America,English,beard
245507,494947,An Exploration in Blue,10.0,1,Post Production,NaN,0,0,False,NaN,...,An Exploration in Blue,A former couple has one last rendezvous on a l...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248287,510731,Underwater Upside Down,10.0,1,Post Production,NaN,0,0,False,NaN,...,Underwater Upside Down,Underwater Upside Down is an oddball comedy ab...,1.832,NaN,NaN,Comedy,NaN,United States of America,English,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192385,763348,Segal,0.0,0,Post Production,NaN,0,0,False,NaN,...,Segal,A documentary focusing on the life and career ...,1.435,/wIkSOOHRyaHm5Qs9CzxE1RDKVHI.jpg,NaN,Documentary,"Ikrzr Productions, Reel Chicago Productions",United States of America,English,NaN
1193082,760497,The Match,0.0,0,Post Production,NaN,0,0,False,/qeUQgQuE5CeZvnlPjwBOr9TKusK.jpg,...,승부,"Two legendary Go players, once student and mas...",0.993,/5hmchi4n7GJnFLz5XGbVMPOqPOx.jpg,NaN,Drama,"Moonlight Film, Acemaker Movieworks, BH Entert...",South Korea,Korean,"based on true story, go"
1193707,761461,Red Butterfly Dream,0.0,0,Post Production,NaN,0,86,False,/yphDa4YquSXzIXIG301HjPO0rz3.jpg,...,Rathu Samanala Heenayak,Three of the four decades of my life have been...,0.600,/p59ssitDU2O9Z8avprQyQmW73kh.jpg,NaN,Fantasy,NaN,NaN,Sinhalese,NaN
1194069,760967,Masculine Feminine,0.0,0,Canceled,NaN,0,0,False,NaN,...,Manab Manabi,A Movie by Subrata Sen,0.600,NaN,NaN,NaN,NaN,NaN,Bengali,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.0,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN

## Filtering Rows Where 'id' is Greater Than a Certain Value

In [407]:
df[df['id'] > 200000]    
# Filtering the DataFrame to include only rows where 'id' is greater than 200000

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
5,293660,Deadpool,7.606,28894,Released,2016-02-09,783100000,108,False,/en971MEXui9diirXlogOrPKmsEn.jpg,...,Deadpool,The origin story of former Special Forces oper...,72.735,/zq8Cl3PNIDGU3iWNRoc5nEZ6pCe.jpg,Witness the beginning of a happy ending.,"Action, Adventure, Comedy","20th Century Fox, The Donners' Company, Genre ...",United States of America,English,"superhero, anti hero, mercenary, based on comi..."
6,299536,Avengers: Infinity War,8.255,27713,Released,2018-04-25,2052415039,149,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,...,Avengers: Infinity War,As the Avengers and their allies have continue...,154.340,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,An entire universe. Once and for all.,"Adventure, Action, Science Fiction",Marvel Studios,United States of America,"English, Xhosa","sacrifice, magic, superhero, based on comic, s..."
15,299534,Avengers: Endgame,8.263,23857,Released,2019-04-24,2800000000,181,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,...,Avengers: Endgame,After the devastating events of Avengers: Infi...,91.756,/or06FN3Dka5tukK1e9sl16pB3iy.jpg,Avenge the fallen.,"Adventure, Science Fiction, Action",Marvel Studios,United States of America,"English, Japanese, Xhosa","superhero, time travel, space travel, time mac..."
18,475557,Joker,8.168,23425,Released,2019-10-01,1074458282,122,False,/hO7KbdvGOtDdeg0W4Y5nKEHeDDh.jpg,...,Joker,"During the 1980s, a failed stand-up comedian i...",54.522,/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg,Put on a happy face.,"Crime, Thriller, Drama","Warner Bros. Pictures, Joint Effort, Village R...","Canada, United States of America",English,"dream, street gang, society, psychopath, clown..."
24,271110,Captain America: Civil War,7.400,21541,Released,2016-04-27,1155046416,147,False,/wdwcOBMkt3zmPQuEMxB3FUtMio2.jpg,...,Captain America: Civil War,"Following the events of Age of Ultron, the col...",70.741,/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg,United we stand. Divided we fall.,"Adventure, Action, Science Fiction",Marvel Studios,United States of America,"Romanian, English, German, Russian","civil war, superhero, based on comic, sequel, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,761152,The Animator as Musician,0.000,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,The Animator as Musician,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,NaN,Documentary,ONF | NFB,NaN,NaN,NaN
1194389,761153,The Beastmaster Chronicles,0.000,0,Released,2020-11-27,0,82,False,NaN,...,The Beastmaster Chronicles,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,NaN,Documentary,Vinegar Syndrome,United States of America,English,NaN
1194390,761155,Under the Great Oak,0.000,0,Released,2019-08-03,0,53,False,NaN,...,Under the Great Oak,A small town wrestles with the responsibility ...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1194391,761158,Dance of the Cookoos,0.000,0,Released,1982-01-01,0,0,False,NaN,...,Dance of the cookoos,Dance of the Cookoos is merged a cinematic cro...,1.186,NaN,NaN,Comedy,Carsten Krüger Film,NaN,NaN,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN

<h1 style="font-size: 31px;">7. Counting Values in a DataFrame</h1>

## Counting Occurrences of a Specific Value in a Column

In [436]:
df[df['original_title'] == "The Dark Knight"].shape[0]  
# Count the number of times "Inception" appears in the 'original_title' column

3

In [438]:
df['original_title'].value_counts().get("The Dark Knight", 0)  
# Count the number of times "Inception" appears in the 'original_title' column

3

<h1 style="font-size: 31px;">8. Handling Missing Values</h1>

## Checking for Missing Values

In [454]:
# Check for missing values
print("\nMissing Values:")
df.isnull().sum()

Missing Values:

id                            0
title                        13
vote_average                  0
vote_count                    0
status                        0
release_date             212019
revenue                       0
runtime                       0
adult                         0
backdrop_path            881619
budget                        0
homepage                1068658
imdb_id                  578060
original_language             0
original_title               13
overview                 249972
popularity                    0
poster_path              387961
tagline                 1027119
genres                   489364
production_companies     661666
production_countries     540882
spoken_languages         520373
keywords                 877806
dtype: int64

## Detecting Missing Values in the DataFrame

In [457]:
# Returns a boolean DataFrame indicating missing values
df.isnull()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,True,True
1194389,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,True
1194390,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,True,True,True,True,True,True
1194391,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,True,False,False,True,True,True
1194392,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,True

## Removing Rows with Missing Values

In [461]:
df.dropna()
#Remove rows with missing values

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192704,760245,Foe,0.000,0,Released,2023-10-06,0,110,False,/tFxAeagQbrjCqjikwvfsLf6ktT7.jpg,...,Foe,Hen & Junior farm a secluded piece of land tha...,15.470,/eTPBizhkX6B9NgzPzkhVIOvwXxZ.jpg,Some people are made for each other.,"Drama, Science Fiction, Romance","See-Saw Films, I Am That, Anonymous Content St...","Australia, United Kingdom, United States of Am...",English,"based on novel or book, married couple, climat..."
1193155,759586,Personal Life of a Hole,0.000,0,Released,2021-06-26,0,62,False,/7aYhxUvktArAN2uBrZgyacoV8wi.jpg,...,Osobní život díry,"A hole gapes in a house wall. A small flaw, so...",0.614,/wLTNjXRK8Ovwt2w14PXdKavaGyG.jpg,„A window is a hole in the wall... or in the r...,Documentary,"Silk Films, Česká televize","Czech Republic, Finland","Czech, English, French",essay film
1193158,759592,A Day with Jose,0.000,0,Released,2019-08-05,0,59,False,/4C5cU3l5kv77MQHiqqse9Ib5Ind.jpg,...,A Day with Jose,Sky Sports News reporter Gary Coterill spends ...,0.600,/vO9eAyDLB5R13MVRhJqcoKa82bt.jpg,"""They Call Me Ze""",Documentary,Sky Sport,United Kingdom,"English, Portuguese","football (soccer), football (soccer) coach"
1193272,759450,A Hole,0.000,0,Released,2019-04-05,0,10,False,/q73iEcM7ygqRxBvl3AYkYZ6IpiJ.jpg,...,A Hole,The world is about to be swallowed by a black ...,0.600,/b6vYzMzTSl3iuZchuB7pVtqVM6l.jpg,"In a black hole apocalypse, a billionaire and ...","Animation, Science Fiction",University of Southern California,United States of America,English,"black hole, doomsday, short film"
1194234,761273,Joji Presents: THE EXTRAVAGANZA,0.000,0,Released,2020-10-23,1000000,72,False,/v8zodxuSVrTsmac9O4No1E3U09B.jpg,...,Joji Presents: THE EXTRAVAGANZA,Joji celebrates the release of his second stud...,1.400,/9ey1AhhDaxuSsLqXqXd8YlOt5Iz.jpg,Welcome to The Extravaganza!,Music,88 Rising,United States of America,"English, Italian",concert

In [465]:
df           
# Displaying the DataFrame

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,761152,The Animator as Musician,0.000,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,The Animator as Musician,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,NaN,Documentary,ONF | NFB,NaN,NaN,NaN
1194389,761153,The Beastmaster Chronicles,0.000,0,Released,2020-11-27,0,82,False,NaN,...,The Beastmaster Chronicles,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,NaN,Documentary,Vinegar Syndrome,United States of America,English,NaN
1194390,761155,Under the Great Oak,0.000,0,Released,2019-08-03,0,53,False,NaN,...,Under the Great Oak,A small town wrestles with the responsibility ...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1194391,761158,Dance of the Cookoos,0.000,0,Released,1982-01-01,0,0,False,NaN,...,Dance of the cookoos,Dance of the Cookoos is merged a cinematic cro...,1.186,NaN,NaN,Comedy,Carsten Krüger Film,NaN,NaN,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN

## Filling Missing Values

In [470]:
df.fillna(7)
# Temporarily replace missing values with 7

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,761152,The Animator as Musician,0.000,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,The Animator as Musician,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,7,Documentary,ONF | NFB,7,7,7
1194389,761153,The Beastmaster Chronicles,0.000,0,Released,2020-11-27,0,82,False,7,...,The Beastmaster Chronicles,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,7,Documentary,Vinegar Syndrome,United States of America,English,7
1194390,761155,Under the Great Oak,0.000,0,Released,2019-08-03,0,53,False,7,...,Under the Great Oak,A small town wrestles with the responsibility ...,0.600,7,7,7,7,7,7,7
1194391,761158,Dance of the Cookoos,0.000,0,Released,1982-01-01,0,0,False,7,...,Dance of the cookoos,Dance of the Cookoos is merged a cinematic cro...,1.186,7,7,Comedy,Carsten Krüger Film,7,7,7
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",7,7,English,7

In [472]:
df['budget'] = df['budget'].fillna(0)  
# Fills missing values in the 'budget' column with 0 permanently

In [474]:
df                  
# Displaying the DataFrame

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,761152,The Animator as Musician,0.000,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,The Animator as Musician,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,NaN,Documentary,ONF | NFB,NaN,NaN,NaN
1194389,761153,The Beastmaster Chronicles,0.000,0,Released,2020-11-27,0,82,False,NaN,...,The Beastmaster Chronicles,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,NaN,Documentary,Vinegar Syndrome,United States of America,English,NaN
1194390,761155,Under the Great Oak,0.000,0,Released,2019-08-03,0,53,False,NaN,...,Under the Great Oak,A small town wrestles with the responsibility ...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1194391,761158,Dance of the Cookoos,0.000,0,Released,1982-01-01,0,0,False,NaN,...,Dance of the cookoos,Dance of the Cookoos is merged a cinematic cro...,1.186,NaN,NaN,Comedy,Carsten Krüger Film,NaN,NaN,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN

<h1 style="font-size: 31px;"> 9. Selecting Data using Indexing</h1>

## Integer-Based Indexing with iloc[]

In [481]:
df.iloc[100000:105000]    
# Selects rows from index 100000 to 105000 using integer-based indexing

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
100000,198521,Sweet Revenge,6.833,6,Released,1976-06-06,0,90,False,/kSxsbQs6mkvNKEJH6B5Au99ew69.jpg,...,Sweet Revenge,A young woman with a long rap sheet who steals...,1.714,/7Cct7dIcrVvuJOgeKHlDxkDUGa0.jpg,There's never been a girl so good at being bad...,"Comedy, Crime",Metro-Goldwyn-Mayer,United States of America,English,"delinquent, porsche, grand theft auto, stolen ..."
100001,643560,Maddy the Model,6.700,6,Released,2020-03-19,0,95,False,NaN,...,Maddy the Model,Madeline Stuart is a fashion celebrity who has...,1.199,/79kQIrL36dIoE4uzHyYPqwBvraN.jpg,NaN,Documentary,B-Reel Films,Sweden,English,"fashion, disability, modeling"
100002,80094,The Apple Game,5.917,6,Released,1978-02-03,0,100,False,/tr8araiwuZbsBVfgI60kPkFLd8r.jpg,...,Hra o jablko,Sarcastic comedy about the Czechoslovakia of t...,1.137,/2ITr17lH8Cl9Y1G7RJwe8Js8syz.jpg,NaN,"Comedy, Drama",Krátký film Praha,Czechoslovakia,Czech,woman director
100003,277595,John Cena - Word Life,7.800,6,Released,2004-01-01,0,53,False,NaN,...,John Cena - Word Life,"Bone-crusher John Cena, one of World Wrestling...",1.692,NaN,NaN,Documentary,WWE Home Video,United States of America,NaN,NaN
100004,81347,Dirty Bomb,3.900,6,Released,2011-09-23,0,83,False,NaN,...,Likainen pommi,Mirccu has a dream job as the PR coordinator o...,1.078,NaN,NaN,Comedy,Juonifilmi,Finland,Finnish,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104995,337563,Pilotos de la muerte,5.300,6,Released,1962-05-02,0,88,False,/iqzFhgZVPe5rFCS93aNfwQ1wAgs.jpg,...,Pilotos de la muerte,A couple of provincial gas station employees t...,1.394,/nMQr2UZLespPG5RrPB1D2Q9E9bM.jpg,NaN,"Adventure, Comedy, Crime",Producciones Sotomayor,Mexico,Spanish,"car race, gas station, pilot, mechanic, couple..."
104996,444452,El alma se serena,6.200,6,Released,1970-01-12,104,0,False,/cHZARywlxn4Dcys7lORCnzvjfsG.jpg,...,El alma se serena,NaN,1.943,/curq2XlnmRMRXNfhs21CSR9sscW.jpg,NaN,Comedy,"Chapalo Film, Universal Films Española",Spain,Spanish,NaN
104997,475969,The Son of Alma Grande,5.200,6,Released,1976-03-04,0,90,False,NaN,...,El hijo de Alma Grande,Some aliens stalk and kidnap humans to take th...,0.600,/ldANM1QCVW128RHlSBimXMMopXH.jpg,NaN,"Horror, Adventure, Action","Belice International, Producciones Fílmicas Ag...",Mexico,Spanish,"extraterrestrial, lucha libre"
104998,103987,Le Surbook,5.400,6,Released,1998-08-05,0,126,False,NaN,...,Le Surbook,"Overbooking : male noun, neologism, method whi...",1.373,/vyVGTQgtRM1US4NHlFPiuuaO81m.jpg,NaN,Comedy,NaN,France,French,NaN
104999,143944,A History of the Blue Movie,5.200,6,Released,1970-10-04,0,116,True,NaN,...,A History of the Blue Movie,A collection of early shorts (a combination of...,0.633,/oWhGslJwKZ89VpkfFoBYFVaniIN.jpg,NaN,NaN,NaN,NaN,English,NaN

In [493]:
df.iloc[10, 1] 
# Fetches movie title from column 'title'

'Forrest Gump'

In [497]:
df.iloc[0:2] 
# Selecting a range of rows (first 2 rows)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."

In [499]:
# Selecting specific rows and columns
df.iloc[0:3, 1:3]

             title  vote_average
0        Inception         8.364
1     Interstellar         8.417
2  The Dark Knight         8.512

## Label-Based Indexing with loc[]

In [504]:
# Selecting a row by label (index)
print(df.loc[100])

id                                                                 313369
title                                                          La La Land
vote_average                                                        7.897
vote_count                                                          15625
status                                                           Released
release_date                                                   2016-11-29
revenue                                                         447407695
runtime                                                               129
adult                                                               False
backdrop_path                            /qJeU7KM4nT2C1WpOrwPcSDGFUWE.jpg
budget                                                           30000000
homepage                                        http://www.lalaland.movie
imdb_id                                                         tt3783958
original_language                                                      en
original_title                                                 La La Land
overview                Mia, an aspiring actress, serves lattes to mov...
popularity                                                         32.009
poster_path                              /uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg
tagline                                    Here's to the fools who dream.
genres                                      Comedy, Drama, Romance, Music
production_companies    Summit Entertainment, Black Label Media, Gilbe...
production_countries                             United States of America
spoken_languages                                                  English
keywords                dancing, dance, jazz, musical, ambition, casti...
Name: 100, dtype: object

In [508]:
# Selecting multiple rows
df.loc[[0, 200, 300]]

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
200,82690,Wreck-It Ralph,7.300,11546,Released,2012-11-01,471222889,101,False,/ziC23LkMYj8gToQQYQGWSGJCLNF.jpg,...,Wreck-It Ralph,"Wreck-It Ralph is the 9-foot-tall, 643-pound v...",46.617,/zWoIgZ7mgmPkaZjG0102BSKFIqQ.jpg,The story of a regular guy just looking for a ...,"Family, Animation, Comedy, Adventure","Walt Disney Animation Studios, Walt Disney Pic...",United States of America,English,"video game, support group, bullying, medal, pr..."
300,1949,Zodiac,7.500,9597,Released,2007-03-02,84785914,157,False,/cYU5msaAPbHRZ3Qm4Y36Fz8wkqX.jpg,...,Zodiac,A cartoonist teams up with an ace reporter and...,36.465,/6YmeO4pB7XTh8P8F960O1uA14JO.jpg,There's more than one way to lose your life to...,"Crime, Drama, Mystery, Thriller","Paramount, Phoenix Pictures, Warner Bros. Pict...",United States of America,English,"newspaper, journalist, california, based on no..."

In [528]:
print(df.loc[:,"budget"])  
# Selects all rows, only the 'budget' column

0          160000000
1          165000000
2          185000000
3          237000000
4          220000000
             ...
1194388            0
1194389            0
1194390            0
1194391            0
1194392            0
Name: budget, Length: 1194393, dtype: int64

In [530]:
print(df.loc[:, ["homepage", "imdb_id"]])  
# All rows, only 'homepage' and 'imdb_id' columns

                                               homepage    imdb_id
0           https://www.warnerbros.com/movies/inception  tt1375666
1                     http://www.interstellarmovie.net/  tt0816692
2        https://www.warnerbros.com/movies/dark-knight/  tt0468569
3                  https://www.avatar.com/movies/avatar  tt0499549
4            https://www.marvel.com/movies/the-avengers  tt0848228
...                                                 ...        ...
1194388                                   http://nfb.ca        NaN
1194389                                             NaN        NaN
1194390                      https://greatoakmovie.com/  tt8335064
1194391                                             NaN  tt0366336
1194392                     https://www.pinkfloyd.film/        NaN

[1194393 rows x 2 columns]

In [532]:
print(df.loc[2, "title"]) 
# Selecting the value from Row 2, Column 'title'

The Dark Knight

<h1 style="font-size: 31px;">10. Filtering Data Using Conditions</h1>

In [549]:
print(df.loc[df["vote_average"] >= 9])  
# Movies with vote average 9 or higher

             id                                              title  \
8879     665399      BTS World Tour: Love Yourself - Japan Edition
11402    596601                               Prison High Pressure
12794    730647                       Break the Silence: The Movie
16379    529414                  Franco Escamilla: por la anécdota
16807    939984  BTS Permission to Dance On Stage - Seoul: Live...
...         ...                                                ...
1157011  809593                                            Transit
1165443  806860  Jessico, Una Historia de Rock en Tiempos Convu...
1188134  756937                                   Call of the Wild
1188502  758948                                              DHONG
1193428  759968                                          Swan Lake

         vote_average  vote_count    status release_date   revenue  runtime  \
8879            9.172         306  Released   2019-10-09         0      231
11402           9.200         210  Released   2019-03-07         0      116
12794           9.154         175  Released   2020-09-10   8954945       90
16379           9.000         118  Released   2018-06-08         0       66
16807           9.018         113  Released   2022-03-12  32600000      195
...               ...         ...       ...          ...       ...      ...
1157011        10.000           0  Released   2013-04-28         0        6
1165443        10.000           0  Released   2012-11-20         0        0
1188134        10.000           0  Released   1992-01-01         0       89
1188502        10.000           0  Released   2020-10-29         0        7
1193428         9.000           0  Released   1998-06-10         0      118

         adult                     backdrop_path  ...  \
8879     False                               NaN  ...
11402     True  /d0t4QfNiITNThGJHVdIXASoU5T9.jpg  ...
12794    False  /8vDzqxZvrp7IdyAI5F8NePWGyEP.jpg  ...
16379    False  /vUKh3q6HO8x8VGTfAw9axL8uEyv.jpg  ...
16807    False  /ttsFffDoso5BIqNugMoQDBI9A34.jpg  ...
...        ...                               ...  ...
1157011  False                               NaN  ...
1165443  False   /LkeJwZPC2FAyV8fuC09qmT33ug.jpg  ...
1188134   True  /hQcVEBOLSnqNFVtR9lvrJZMVVea.jpg  ...
1188502  False                               NaN  ...
1193428  False  /9SzcMvR2bSbtLPe19wAZWdQghbg.jpg  ...

                                            original_title  \
8879         BTS World Tour: Love Yourself - Japan Edition
11402                            Prison sous haute tension
12794                                    브레이크 더 사일런스: 더 무비
16379                    Franco Escamilla: por la anécdota
16807    BTS Permission to Dance On Stage - Seoul: Live...
...                                                    ...
1157011                                            Transit
1165443  Jessico, Una Historia de Rock en Tiempos Convu...
1188134                                   Call of the Wild
1188502                                              DHONG
1193428                                          Swan Lake

                                                  overview popularity  \
8879     BTS perform their Japan concert at Tokyo Dome ...      4.892
11402    Behind the scenes in a prison with a very spec...    297.563
12794    K-pop sensation BTS embark on their 2019 'Love...      7.198
16379    Mexican stand-up comedian Franco Escamilla dra...      7.013
16807    Join us as BTS and ARMY become one once again ...      6.877
...                                                    ...        ...
1157011  A small-time, down-on-his-luck actor is visite...      0.600
1165443                                                NaN      0.600
1188134  Filmed in the wilderness of French Canada, thi...      0.600
1188502  A man murders a Dhongi Baba, steals a briefcas...      0.600
1193428  Contemporary dance company Adventures In Motio...      0.600

                              poster_path  \
8879     /dA0MVEjNOP3GmWigu6Cs3I399Zt.jpg
11402    /4ZkhtGaqU14pyTxpDpqDemaYb4D.jpg
12794    /k1VK2L971GmEevIjFbjcimxSeMx.jpg
16379    /f4iwq1hkcAS9xkUGtpeDBVnhfFb.jpg
16807    /d5Qg9sbntjqmuswpIuF7BltuUZq.jpg
...                                   ...
1157011  /62hIfY2H1cBA759i0qqcH4wVVFN.jpg
1165443  /wBmDetyzPA9pV8HWlUVFXgzsuUS.jpg
1188134  /s9BokWS60gDVJysI5z8uJtK6psX.jpg
1188502  /n82vOcfr7jmN28KmySl9dRyZhKb.jpg
1193428  /5MYqdeLa0WlWj4a7cOz27bbap6n.jpg

                                                   tagline  \
8879                                                   NaN
11402                                                  NaN
12794                                             Borahae.
16379                                                  NaN
16807                                                  NaN
...                                                    ...
1157011         Facts and truth... are not the same things
1165443                                                NaN
1188134               Starring 11 hot French Canadian men!
1188502                                                NaN
1193428  Olivier Award-winning production featuring the...

                         genres                          production_companies  \
8879         Music, Documentary                         Big Hit Entertainment
11402                       NaN                                   Marc Dorcel
12794        Music, Documentary           Big Hit Entertainment, CJ CGV, HYBE
16379                    Comedy                                           NaN
16807                     Music                   HYBE, Big Hit Entertainment
...                         ...                                           ...
1157011  Science Fiction, Drama                          Shredder Productions
1165443      Music, Documentary                        PopArt Music Argentina
1188134                     NaN                     Kristen Bjorn Productions
1188502                     NaN                                           NaN
1193428                   Music  Adventures in Motion Pictures, NVC Arts, BBC

             production_countries  spoken_languages  \
8879                  South Korea            Korean
11402                      France            French
12794                 South Korea            Korean
16379                      Mexico           Spanish
16807                 South Korea   English, Korean
...                           ...               ...
1157011  United States of America           English
1165443                 Argentina  Spanish, English
1188134                    Canada            French
1188502                       NaN               NaN
1193428            United Kingdom               NaN

                                                  keywords
8879                 making of, concert film, choreography
11402                                               prison
12794    pop star, pop music, concert film, boy band, k...
16379                            comedian, stand-up comedy
16807    concert, live performance, concert film, k-pop...
...                                                    ...
1157011                         alien, vermont, short film
1165443          argentina, babasónicos, jessico, dargelos
1188134  sex outdoors, male bonding, gay pornography, f...
1188502                                                NaN
1193428  ballet, swan lake, ballet performance, contemp...

[36105 rows x 24 columns]

<h1 style="font-size: 31px;">11. Handling Duplicates</h1>

## Checking for Duplicates

In [555]:
# Remove duplicate rows
print("\nDuplicate Rows:", df.duplicated().sum())

Duplicate Rows: 371

## Removing Duplicate Rows

In [558]:
df.drop_duplicates(inplace=True) 
# Remove duplicate rows permanently
df

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,761152,The Animator as Musician,0.000,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,The Animator as Musician,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,NaN,Documentary,ONF | NFB,NaN,NaN,NaN
1194389,761153,The Beastmaster Chronicles,0.000,0,Released,2020-11-27,0,82,False,NaN,...,The Beastmaster Chronicles,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,NaN,Documentary,Vinegar Syndrome,United States of America,English,NaN
1194390,761155,Under the Great Oak,0.000,0,Released,2019-08-03,0,53,False,NaN,...,Under the Great Oak,A small town wrestles with the responsibility ...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1194391,761158,Dance of the Cookoos,0.000,0,Released,1982-01-01,0,0,False,NaN,...,Dance of the cookoos,Dance of the Cookoos is merged a cinematic cro...,1.186,NaN,NaN,Comedy,Carsten Krüger Film,NaN,NaN,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN

<h1 style="font-size: 31px;">12. Adding and Removing Columns</h1>

## Adding a New Column

In [564]:
df["new_column2"] = df["budget"] + df["revenue"]
df

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords,new_column2
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",985532764
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",866729206
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",1189558444
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",3160706026
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",1738815515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,761152,The Animator as Musician,0.000,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,NaN,Documentary,ONF | NFB,NaN,NaN,NaN,0
1194389,761153,The Beastmaster Chronicles,0.000,0,Released,2020-11-27,0,82,False,NaN,...,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,NaN,Documentary,Vinegar Syndrome,United States of America,English,NaN,0
1194390,761155,Under the Great Oak,0.000,0,Released,2019-08-03,0,53,False,NaN,...,A small town wrestles with the responsibility ...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1194391,761158,Dance of the Cookoos,0.000,0,Released,1982-01-01,0,0,False,NaN,...,Dance of the Cookoos is merged a cinematic cro...,1.186,NaN,NaN,Comedy,Carsten Krüger Film,NaN,NaN,NaN,0
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN,0

## Dropping a Column

In [567]:
df = df.drop('new_column2', axis=1)
df
# Dropping a column named 'new_column'

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,761152,The Animator as Musician,0.000,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,The Animator as Musician,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,NaN,Documentary,ONF | NFB,NaN,NaN,NaN
1194389,761153,The Beastmaster Chronicles,0.000,0,Released,2020-11-27,0,82,False,NaN,...,The Beastmaster Chronicles,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,NaN,Documentary,Vinegar Syndrome,United States of America,English,NaN
1194390,761155,Under the Great Oak,0.000,0,Released,2019-08-03,0,53,False,NaN,...,Under the Great Oak,A small town wrestles with the responsibility ...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1194391,761158,Dance of the Cookoos,0.000,0,Released,1982-01-01,0,0,False,NaN,...,Dance of the cookoos,Dance of the Cookoos is merged a cinematic cro...,1.186,NaN,NaN,Comedy,Carsten Krüger Film,NaN,NaN,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN

In [575]:
df   
#Displaying DataFrame

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194388,761152,The Animator as Musician,0.000,0,Released,2006-01-01,0,0,False,/5Q6V2m00ZFmRP2mCaMiiSNvdWYQ.jpg,...,The Animator as Musician,Norman McLaren's work bears the imprint of his...,0.600,/6yddnWzoYe8LdWB2rUUPnHOXqdI.jpg,NaN,Documentary,ONF | NFB,NaN,NaN,NaN
1194389,761153,The Beastmaster Chronicles,0.000,0,Released,2020-11-27,0,82,False,NaN,...,The Beastmaster Chronicles,Documentary about the making of the film The B...,2.425,/kXwgu3VAC1CnnJ3xmhvBCyAFN2H.jpg,NaN,Documentary,Vinegar Syndrome,United States of America,English,NaN
1194390,761155,Under the Great Oak,0.000,0,Released,2019-08-03,0,53,False,NaN,...,Under the Great Oak,A small town wrestles with the responsibility ...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1194391,761158,Dance of the Cookoos,0.000,0,Released,1982-01-01,0,0,False,NaN,...,Dance of the cookoos,Dance of the Cookoos is merged a cinematic cro...,1.186,NaN,NaN,Comedy,Carsten Krüger Film,NaN,NaN,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN

<h1 style="font-size: 31px;">13. Sorting Data</h1>

## Sorting by a Column

In [581]:
df = df.sort_values(by="revenue", ascending=False)
print("\nSorted Data by revenue:")
df

Sorted Data by revenue:

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
604852,1407985,babben: the movie,0.000,0,Released,NaN,4999999999,999,False,NaN,...,babben: the movie,the cool movie about babben its very specilala...,0.600,/t8JjeieVKwhLKeBSFFFnIlj3yuk.jpg,babben,NaN,NaN,NaN,NaN,NaN
263436,1270893,TikTok Rizz Party,10.000,1,Released,2024-04-01,3000000000,180,False,/5dO66jbuKb2EDGZDqLjRmNMrHB1.jpg,...,TikTok Rizz Party,"a band of brothers, torn apart by the constant...",0.000,/db5pfZIeNLuZawkDXYylNE1opJO.jpg,NaN,"Drama, Comedy",Warner Bros.,United States of America,NaN,"party, tiktok, rizz"
746489,1224207,Adventures in Bora Bora,0.000,0,Released,2023-08-23,3000000000,5,False,/gkoq31q4fe9L1cCooZI5y61FlN7.jpg,...,Adventures in Bora Bora,"The adventures in Bora Bora, is an astonishing...",0.000,/hx51R9mVvy7tRxY9flKtfC4m2A6.jpg,(English),"Horror, War",NaN,NaN,English,NaN
749020,1236552,Bee Movie,0.000,0,Released,NaN,2930000000,91,False,NaN,...,Bee Movie,"Fresh out of college, Barry the Bee finds the ...",1.400,/y6NkzOcroqr1YgToGipXSq9LzQH.jpg,"""Get the nectar, make the honey, get the polle...",NaN,NaN,NaN,NaN,NaN
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409053,1434424,Java Jive,0.000,0,In Production,2025-02-27,0,17,False,/kBqs0GAtRg0nraNya3xc448A2RR.jpg,...,Java Jive,A thirsty young man tries to resist a hot drink.,1.400,/ga09S7rPMKgp3nMyva5ogiAT7IZ.jpg,NaN,Comedy,Burgindie Pictures,NaN,NaN,"coffee, mormon, romantic comedy"
409052,1448850,ANRI IN CONCERT,0.000,0,Released,1984-05-12,0,58,False,NaN,...,杏里イン・コンサート,Centered around the enthusiastic live performa...,0.600,/nqnPH7z4T1ooTKHywMvYk82DyBQ.jpg,NaN,Music,NaN,Japan,Japanese,NaN
409051,1161762,Gordon,0.000,0,Released,2015-08-06,0,5,False,/6WZYvcccXMDNFvC2eklFIwR9yhg.jpg,...,Gordon,28 years from his last Broom Cupboard appearnc...,0.671,/qWoT8DFuFFb2DYzRdp6wcLH4NAk.jpg,NaN,Comedy,BBC,NaN,NaN,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN
188628,339294,Some Bears,7.000,2,Released,2013-05-15,-12,8,False,NaN,...,Some Bears,A young man slips into a world of delusion aft...,0.600,NaN,"Bears, known in the wild for their cuddliness",NaN,NaN,United States of America,English,NaN

<h1 style="font-size: 31px;">14. Grouping and Aggregation</h1>

## Grouping by 'genres' and calculating average 'revenue'

In [589]:
grouped_df = df.groupby('genres')['revenue'].mean()
print("Average revenue by genres:")
print(grouped_df)

Average revenue by genres:
genres
Action                                                          3.410305e+05
Action, Action                                                  0.000000e+00
Action, Action, Crime                                           0.000000e+00
Action, Action, Thriller                                        0.000000e+00
Action, Adventure                                               3.003399e+06
                                                                    ...
Western, War, Adventure, History, Science Fiction, Animation    0.000000e+00
Western, War, Drama                                             0.000000e+00
Western, War, Drama, Music                                      0.000000e+00
Western, War, Romance                                           0.000000e+00
Western, War, Thriller                                          0.000000e+00
Name: revenue, Length: 13680, dtype: float64

## Grouping by 'genres' and calculating median 'revenue'

In [594]:
grouped_df = df.groupby('genres')['revenue'].median()
print("Median revenue by genres:")
print(grouped_df)

Median revenue by genres:
genres
Action                                                          0.0
Action, Action                                                  0.0
Action, Action, Crime                                           0.0
Action, Action, Thriller                                        0.0
Action, Adventure                                               0.0
                                                               ...
Western, War, Adventure, History, Science Fiction, Animation    0.0
Western, War, Drama                                             0.0
Western, War, Drama, Music                                      0.0
Western, War, Romance                                           0.0
Western, War, Thriller                                          0.0
Name: revenue, Length: 13680, dtype: float64

## Grouping by 'genres' and calculating variance of 'revenue'

In [599]:
grouped_df = df.groupby('genres')['revenue'].var()
print("Variance of revenue by genres:")
print(grouped_df)

Variance of revenue by genres:
genres
Action                                                          1.407738e+14
Action, Action                                                           NaN
Action, Action, Crime                                                    NaN
Action, Action, Thriller                                                 NaN
Action, Adventure                                               1.486479e+15
                                                                    ...
Western, War, Adventure, History, Science Fiction, Animation             NaN
Western, War, Drama                                             0.000000e+00
Western, War, Drama, Music                                               NaN
Western, War, Romance                                                    NaN
Western, War, Thriller                                                   NaN
Name: revenue, Length: 13680, dtype: float64

## Grouping by 'genres' and calculating standard deviation of 'revenue'

In [604]:
grouped_df = df.groupby('genres')['revenue'].std()
print("Standard Deviation of revenue by genres:")
print(grouped_df)

Standard Deviation of revenue by genres:
genres
Action                                                          1.186481e+07
Action, Action                                                           NaN
Action, Action, Crime                                                    NaN
Action, Action, Thriller                                                 NaN
Action, Adventure                                               3.855488e+07
                                                                    ...
Western, War, Adventure, History, Science Fiction, Animation             NaN
Western, War, Drama                                             0.000000e+00
Western, War, Drama, Music                                               NaN
Western, War, Romance                                                    NaN
Western, War, Thriller                                                   NaN
Name: revenue, Length: 13680, dtype: float64

<h1 style="font-size: 31px;">15. Renaming a Column</h1>

## Renaming the Column 'title' to 'movie_title'

In [610]:
df = df.rename(columns={"title": "movie_title"})
# Renaming the column 'title' to 'movie_title' in the DataFrame
# The columns parameter is used to specify the old and new column names
# The change is temporary unless reassigned to df

In [612]:
df         
# Displaying the DataFrame

,id,movie_title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
604852,1407985,babben: the movie,0.000,0,Released,NaN,4999999999,999,False,NaN,...,babben: the movie,the cool movie about babben its very specilala...,0.600,/t8JjeieVKwhLKeBSFFFnIlj3yuk.jpg,babben,NaN,NaN,NaN,NaN,NaN
263436,1270893,TikTok Rizz Party,10.000,1,Released,2024-04-01,3000000000,180,False,/5dO66jbuKb2EDGZDqLjRmNMrHB1.jpg,...,TikTok Rizz Party,"a band of brothers, torn apart by the constant...",0.000,/db5pfZIeNLuZawkDXYylNE1opJO.jpg,NaN,"Drama, Comedy",Warner Bros.,United States of America,NaN,"party, tiktok, rizz"
746489,1224207,Adventures in Bora Bora,0.000,0,Released,2023-08-23,3000000000,5,False,/gkoq31q4fe9L1cCooZI5y61FlN7.jpg,...,Adventures in Bora Bora,"The adventures in Bora Bora, is an astonishing...",0.000,/hx51R9mVvy7tRxY9flKtfC4m2A6.jpg,(English),"Horror, War",NaN,NaN,English,NaN
749020,1236552,Bee Movie,0.000,0,Released,NaN,2930000000,91,False,NaN,...,Bee Movie,"Fresh out of college, Barry the Bee finds the ...",1.400,/y6NkzOcroqr1YgToGipXSq9LzQH.jpg,"""Get the nectar, make the honey, get the polle...",NaN,NaN,NaN,NaN,NaN
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409053,1434424,Java Jive,0.000,0,In Production,2025-02-27,0,17,False,/kBqs0GAtRg0nraNya3xc448A2RR.jpg,...,Java Jive,A thirsty young man tries to resist a hot drink.,1.400,/ga09S7rPMKgp3nMyva5ogiAT7IZ.jpg,NaN,Comedy,Burgindie Pictures,NaN,NaN,"coffee, mormon, romantic comedy"
409052,1448850,ANRI IN CONCERT,0.000,0,Released,1984-05-12,0,58,False,NaN,...,杏里イン・コンサート,Centered around the enthusiastic live performa...,0.600,/nqnPH7z4T1ooTKHywMvYk82DyBQ.jpg,NaN,Music,NaN,Japan,Japanese,NaN
409051,1161762,Gordon,0.000,0,Released,2015-08-06,0,5,False,/6WZYvcccXMDNFvC2eklFIwR9yhg.jpg,...,Gordon,28 years from his last Broom Cupboard appearnc...,0.671,/qWoT8DFuFFb2DYzRdp6wcLH4NAk.jpg,NaN,Comedy,BBC,NaN,NaN,NaN
1194392,1450576,Pink Floyd At Pompeii - MCMLXXII,0.000,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,"Music, Documentary",NaN,NaN,English,NaN
188628,339294,Some Bears,7.000,2,Released,2013-05-15,-12,8,False,NaN,...,Some Bears,A young man slips into a world of delusion aft...,0.600,NaN,"Bears, known in the wild for their cuddliness",NaN,NaN,United States of America,English,NaN

<h1 style="font-size: 31px;">16. Resetting and Setting Index</h1>

## Setting a Multi-Level Index

In [638]:
df = df.set_index(["movie_title", "vote_average"])
# Setting 'movie_title' and 'vote_average' as the new multi-level index of the DataFrame
# This helps in organizing data based on movie titles and their average ratings
# The change is temporary unless reassigned to df

In [639]:
df
# Displaying the DataFrame

,,id,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,budget,homepage,...,original_language,original_title,overview,popularity,poster_path,tagline,production_companies,production_countries,spoken_languages,keywords
movie_title,vote_average,,,,,,,,,,,,,,,,,,,,,
babben: the movie,0.000,1407985,0,Released,NaN,4999999999,999,False,NaN,100,https://babbenmovie.neocities.org/,...,en,babben: the movie,the cool movie about babben its very specilala...,0.600,/t8JjeieVKwhLKeBSFFFnIlj3yuk.jpg,babben,NaN,NaN,NaN,NaN
TikTok Rizz Party,10.000,1270893,1,Released,2024-04-01,3000000000,180,False,/5dO66jbuKb2EDGZDqLjRmNMrHB1.jpg,250000000,NaN,...,en,TikTok Rizz Party,"a band of brothers, torn apart by the constant...",0.000,/db5pfZIeNLuZawkDXYylNE1opJO.jpg,NaN,Warner Bros.,United States of America,NaN,"party, tiktok, rizz"
Adventures in Bora Bora,0.000,1224207,0,Released,2023-08-23,3000000000,5,False,/gkoq31q4fe9L1cCooZI5y61FlN7.jpg,800000000,https://m.youtube.com/watch?v=F-QGRigpYmw&pp=y...,...,en,Adventures in Bora Bora,"The adventures in Bora Bora, is an astonishing...",0.000,/hx51R9mVvy7tRxY9flKtfC4m2A6.jpg,(English),NaN,NaN,English,NaN
Bee Movie,0.000,1236552,0,Released,NaN,2930000000,91,False,NaN,150000000,NaN,...,en,Bee Movie,"Fresh out of college, Barry the Bee finds the ...",1.400,/y6NkzOcroqr1YgToGipXSq9LzQH.jpg,"""Get the nectar, make the honey, get the polle...",NaN,NaN,NaN,NaN
Avatar,7.573,19995,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,237000000,https://www.avatar.com/movies/avatar,...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Java Jive,0.000,1434424,0,In Production,2025-02-27,0,17,False,/kBqs0GAtRg0nraNya3xc448A2RR.jpg,0,NaN,...,en,Java Jive,A thirsty young man tries to resist a hot drink.,1.400,/ga09S7rPMKgp3nMyva5ogiAT7IZ.jpg,NaN,Burgindie Pictures,NaN,NaN,"coffee, mormon, romantic comedy"
ANRI IN CONCERT,0.000,1448850,0,Released,1984-05-12,0,58,False,NaN,0,NaN,...,ja,杏里イン・コンサート,Centered around the enthusiastic live performa...,0.600,/nqnPH7z4T1ooTKHywMvYk82DyBQ.jpg,NaN,NaN,Japan,Japanese,NaN
Gordon,0.000,1161762,0,Released,2015-08-06,0,5,False,/6WZYvcccXMDNFvC2eklFIwR9yhg.jpg,0,https://www.bbc.co.uk/taster/pilots/gordon,...,en,Gordon,28 years from his last Broom Cupboard appearnc...,0.671,/qWoT8DFuFFb2DYzRdp6wcLH4NAk.jpg,NaN,BBC,NaN,NaN,NaN
Pink Floyd At Pompeii - MCMLXXII,0.000,1450576,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,0,https://www.pinkfloyd.film/,...,en,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,NaN,NaN,English,NaN
Some Bears,7.000,339294,2,Released,2013-05-15,-12,8,False,NaN,12,NaN,...,en,Some Bears,A young man slips into a world of delusion aft...,0.600,NaN,"Bears, known in the wild for their cuddliness",NaN,United States of America,English,NaN

## Resetting the Index

In [643]:
df = df.reset_index()
# Resetting the index of the DataFrame, converting multi-level indices back into columns
# This restores 'movie_title' and 'vote_average' as regular columns if they were previously set as an index
# The change is temporary unless reassigned to df

In [645]:
df 
# Displaying the DataFrame

,movie_title,vote_average,id,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_language,original_title,overview,popularity,poster_path,tagline,production_companies,production_countries,spoken_languages,keywords
0,babben: the movie,0.000,1407985,0,Released,NaN,4999999999,999,False,NaN,...,en,babben: the movie,the cool movie about babben its very specilala...,0.600,/t8JjeieVKwhLKeBSFFFnIlj3yuk.jpg,babben,NaN,NaN,NaN,NaN
1,TikTok Rizz Party,10.000,1270893,1,Released,2024-04-01,3000000000,180,False,/5dO66jbuKb2EDGZDqLjRmNMrHB1.jpg,...,en,TikTok Rizz Party,"a band of brothers, torn apart by the constant...",0.000,/db5pfZIeNLuZawkDXYylNE1opJO.jpg,NaN,Warner Bros.,United States of America,NaN,"party, tiktok, rizz"
2,Adventures in Bora Bora,0.000,1224207,0,Released,2023-08-23,3000000000,5,False,/gkoq31q4fe9L1cCooZI5y61FlN7.jpg,...,en,Adventures in Bora Bora,"The adventures in Bora Bora, is an astonishing...",0.000,/hx51R9mVvy7tRxY9flKtfC4m2A6.jpg,(English),NaN,NaN,English,NaN
3,Bee Movie,0.000,1236552,0,Released,NaN,2930000000,91,False,NaN,...,en,Bee Movie,"Fresh out of college, Barry the Bee finds the ...",1.400,/y6NkzOcroqr1YgToGipXSq9LzQH.jpg,"""Get the nectar, make the honey, get the polle...",NaN,NaN,NaN,NaN
4,Avatar,7.573,19995,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194017,Java Jive,0.000,1434424,0,In Production,2025-02-27,0,17,False,/kBqs0GAtRg0nraNya3xc448A2RR.jpg,...,en,Java Jive,A thirsty young man tries to resist a hot drink.,1.400,/ga09S7rPMKgp3nMyva5ogiAT7IZ.jpg,NaN,Burgindie Pictures,NaN,NaN,"coffee, mormon, romantic comedy"
1194018,ANRI IN CONCERT,0.000,1448850,0,Released,1984-05-12,0,58,False,NaN,...,ja,杏里イン・コンサート,Centered around the enthusiastic live performa...,0.600,/nqnPH7z4T1ooTKHywMvYk82DyBQ.jpg,NaN,NaN,Japan,Japanese,NaN
1194019,Gordon,0.000,1161762,0,Released,2015-08-06,0,5,False,/6WZYvcccXMDNFvC2eklFIwR9yhg.jpg,...,en,Gordon,28 years from his last Broom Cupboard appearnc...,0.671,/qWoT8DFuFFb2DYzRdp6wcLH4NAk.jpg,NaN,BBC,NaN,NaN,NaN
1194020,Pink Floyd At Pompeii - MCMLXXII,0.000,1450576,0,Post Production,2025-04-24,0,85,False,/7U5kz9xhYEJFiOfbWDMSM7SZlm7.jpg,...,en,Pink Floyd At Pompeii - MCMLXXII,This meticulous restoration of the groundbreak...,0.712,/coHr0ko4y7Sa7v00XdwmXn8MOTo.jpg,The groundbreaking 1972 film directed by Adria...,NaN,NaN,English,NaN
1194021,Some Bears,7.000,339294,2,Released,2013-05-15,-12,8,False,NaN,...,en,Some Bears,A young man slips into a world of delusion aft...,0.600,NaN,"Bears, known in the wild for their cuddliness",NaN,United States of America,English,NaN

<h1 style="font-size: 31px;">17. Get the dimensions of the DataFrame</h1>

In [648]:
df.shape

(1194022, 23)